// IF ELSE STATEMENT IN C

/*
    DEFINE :- IT IS USED TO PERFORM OPERATION BASED ON SOME CONDITIONS

    ~ TYPE OF IF ELSE STATEMENTS IN C 
    1) IF STATEMENT
    2) IF ELSE STATEMENT
    3) IF ELSE IF LADDER STATMENT
    4) NESTED IF STATEMENT
*/